import "./globals.scss";
import Header from "../../components/Header/Header";
import Footer from "../../components/Footer/Footer";
import ThemeProvider from "../../components/Context/ThemeProvider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className='body'>
      <ThemeProvider>
        <div className="wrapper">
          <Header />
            {children}
          <Footer />
        </div>
      </ThemeProvider>
      </body>
    </html>
  );
}
